using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace Weakly
{
    /// <summary>
    /// A weak event source that does not hold any strong reference to the event listeners.
    /// </summary>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    public abstract class WeakEventSourceBase<TEventArgs>
    {
        private readonly List<WeakAction<object, TEventArgs>> _eventHandlerEntries = new List<WeakAction<object, TEventArgs>>();
        private WeakReference _gcSentinel = new WeakReference(new object());

        #region Cleanup handling

        private bool IsCleanupNeeded()
        {
            if (_gcSentinel.Target == null)
            {
                _gcSentinel = new WeakReference(new object());
                return true;
            }

            return false;
        }

        private void CleanAbandonedItems()
        {
            for (var i = _eventHandlerEntries.Count - 1; i >= 0; i--)
            {
                var entry = _eventHandlerEntries[i];
                if (!entry.IsAlive)
                    _eventHandlerEntries.RemoveAt(i);
            }
        }

        private void CleanIfNeeded()
        {
            if (IsCleanupNeeded())
            {
                CleanAbandonedItems();
            }
        }

        #endregion

        /// <summary>
        /// Adds the specified event handler.
        /// </summary>
        /// <param name="eventHandler">The event handler.</param>
        protected void Add(Delegate eventHandler)
        {
            if (eventHandler == null) return;
            if (eventHandler.Target == null)
                throw new ArgumentException("Cannot create weak event to static method.");

            var declaringType = eventHandler.Method.DeclaringType;
            if (declaringType != null && declaringType.GetCustomAttributes(typeof(CompilerGeneratedAttribute), false).Length != 0)
                throw new ArgumentException("Cannot create weak event to anonymous method with closure.");

            lock (_eventHandlerEntries)
            {
                CleanIfNeeded();
                _eventHandlerEntries.Add(new WeakAction<object, TEventArgs>(eventHandler.Target, eventHandler.Method));
            }
        }

        /// <summary>
        /// Removes the specified event handler.
        /// </summary>
        /// <param name="eventHandler">The event handler.</param>
        protected void Remove(Delegate eventHandler)
        {
            if (eventHandler == null) return;

            lock (_eventHandlerEntries)
            {
                CleanIfNeeded();

                for (var i = _eventHandlerEntries.Count - 1; i >= 0; i--)
                {
                    var entry = _eventHandlerEntries[i];
                    var target = entry.Target;

                    if (target == eventHandler.Target && entry.Method.MethodHandle == eventHandler.Method.MethodHandle)
                    {
                        _eventHandlerEntries.RemoveAt(i);
                        break;
                    }
                }
            }
        }

        /// <summary>
        /// Raises the event.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">An object that contains the event data.</param>
        public void Raise(object sender, TEventArgs e)
        {
            WeakAction<object, TEventArgs>[] invocationList;
            lock (_eventHandlerEntries)
            {
                CleanIfNeeded();
                invocationList = _eventHandlerEntries.ToArray();
            }

            OnRaise(sender, e);

            foreach (var entry in invocationList)
            {
                entry.Invoke(sender, e);
            }
        }

        /// <summary>
        /// Called when the event is raised.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">An object that contains the event data.</param>
        protected abstract void OnRaise(object sender, TEventArgs e);
    }

    /// <summary>
    /// A weak event source that does not hold any strong reference to the event listeners.
    /// </summary>
    public class WeakEventSource : WeakEventSourceBase<EventArgs>
    {
        private EventHandler _staticEventHandlers;

        /// <summary>
        /// Adds the specified event handler.
        /// </summary>
        /// <param name="eventHandler">The event handler.</param>
        public void Add(EventHandler eventHandler)
        {
            if (eventHandler == null) return;
            if (eventHandler.Target == null)
            {
                _staticEventHandlers += eventHandler;
                return;
            }

            base.Add(eventHandler);
        }

        /// <summary>
        /// Removes the specified event handler.
        /// </summary>
        /// <param name="eventHandler">The event handler.</param>
        public void Remove(EventHandler eventHandler)
        {
            if (eventHandler == null) return;
            if (eventHandler.Target == null)
            {
                _staticEventHandlers -= eventHandler;
                return;
            }

            base.Remove(eventHandler);
        }

        /// <summary>
        /// Notifies all static event handlers.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">An object that contains the event data.</param>
        protected override void OnRaise(object sender, EventArgs e)
        {
            var staticHandlers = _staticEventHandlers;
            if (staticHandlers != null)
            {
                staticHandlers(sender, e);
            }
        }
    }

    /// <summary>
    /// A weak event source that does not hold any strong reference to the event listeners.
    /// </summary>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    public class WeakEventSource<TEventArgs> : WeakEventSourceBase<TEventArgs>
        where TEventArgs : EventArgs
    {
        private EventHandler<TEventArgs> _staticEventHandlers;

        /// <summary>
        /// Adds the specified event handler.
        /// </summary>
        /// <param name="eventHandler">The event handler.</param>
        public void Add(EventHandler<TEventArgs> eventHandler)
        {
            if (eventHandler == null) return;
            if (eventHandler.Target == null)
            {
                _staticEventHandlers += eventHandler;
                return;
            }

            base.Add(eventHandler);
        }

        /// <summary>
        /// Removes the specified event handler.
        /// </summary>
        /// <param name="eventHandler">The event handler.</param>
        public void Remove(EventHandler<TEventArgs> eventHandler)
        {
            if (eventHandler == null) return;
            if (eventHandler.Target == null)
            {
                _staticEventHandlers -= eventHandler;
                return;
            }

            base.Remove(eventHandler);
        }

        /// <summary>
        /// Notifies all static event handlers.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">An object that contains the event data.</param>
        protected override void OnRaise(object sender, TEventArgs e)
        {
            var staticHandlers = _staticEventHandlers;
            if (staticHandlers != null)
            {
                staticHandlers(sender, e);
            }
        }
    }
}
